{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logging",
   "type": "table",
   "gridPos": { "h": 20, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum by(method) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
   "targets": [
    { "expr": "active_users_ratio", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "sum by(result) (rate(auth_attempts_total{result=\"success\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(result) (rate(auth_attempts_total{result=\"failure\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and Memory usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_percent", "legendFormat": "CPU usage" },
    { "expr": "system_memory_percent", "legendFormat": "Memory usage" }
   ]
  },
  {
   "title": "Pizzas purchased per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 43 },
   "targets": [
    { "expr": "rate(pizza_sold_total[1m])", "legendFormat": "Pizzas sold" },
    {
     "expr": "rate(pizza_failed_total[$__rate_interval])",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pizza_revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue per minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(pizza_revenue_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_latency_avg_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 61 },
   "targets": [
    {
     "expr": "request_latency_avg_milliseconds",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_latency_avg_milliseconds / 1000",
     "legendFormat": "Seconds"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 69 },
   "targets": [
    {
     "expr": "pizza_latency_avg_milliseconds / 1000",
     "legendFormat": "Pizza creation latency"
    }
   ]
  }
 ]
}